name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 프로젝트 경로로 이동
            cd /var/www/audit
            
            # 최신 코드 받기
            git pull origin main
            
            # 의존성 설치 및 빌드
            npm install
            npm run build
            
            # 앱 재시작 (없으면 시작)
            pm2 reload audit-app || pm2 start npm --name "audit-app" -- start
